//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TepihServisManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dostava
    {
        public int DostavaID { get; set; }
        public string Adresa { get; set; }
        public Nullable<System.DateTime> DatumDostave { get; set; }
        public int NarudzbinaID { get; set; }
    
        public virtual Narudzbina Narudzbina { get; set; }
    }
}
