//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TepihServisManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Komentar
    {
        public int KomentarID { get; set; }
        public string Tekst { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public int KlijentID { get; set; }
    
        public virtual Klijent Klijent { get; set; }
    }
}
