//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TepihServisManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TepihServisDBEntities1 : DbContext
    {
        public TepihServisDBEntities1()
            : base("name=TepihServisDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Dostava> Dostava { get; set; }
        public virtual DbSet<Klijent> Klijent { get; set; }
        public virtual DbSet<Komentar> Komentar { get; set; }
        public virtual DbSet<Korisnik> Korisnik { get; set; }
        public virtual DbSet<Narudzbina> Narudzbina { get; set; }
        public virtual DbSet<Ocjena> Ocjena { get; set; }
        public virtual DbSet<StatusNarudzbine> StatusNarudzbine { get; set; }
        public virtual DbSet<Tepih> Tepih { get; set; }
        public virtual DbSet<Usluga> Usluga { get; set; }
        public virtual DbSet<Zaposleni> Zaposleni { get; set; }
        public virtual DbSet<StavkaNarudzbine> StavkaNarudzbine { get; set; }
    
        public virtual ObjectResult<Sp_FiltrirajNarudzbine_Result> Sp_FiltrirajNarudzbine(Nullable<int> statusID, Nullable<int> klijentID)
        {
            var statusIDParameter = statusID.HasValue ?
                new ObjectParameter("StatusID", statusID) :
                new ObjectParameter("StatusID", typeof(int));
    
            var klijentIDParameter = klijentID.HasValue ?
                new ObjectParameter("KlijentID", klijentID) :
                new ObjectParameter("KlijentID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_FiltrirajNarudzbine_Result>("Sp_FiltrirajNarudzbine", statusIDParameter, klijentIDParameter);
        }
    }
}
