//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TepihServisManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudzbina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Narudzbina()
        {
            this.Dostava = new HashSet<Dostava>();
            this.StavkaNarudzbine = new HashSet<StavkaNarudzbine>();
        }
    
        public int NarudzbinaID { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public int KlijentID { get; set; }
        public int StatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dostava> Dostava { get; set; }
        public virtual Klijent Klijent { get; set; }
        public virtual StatusNarudzbine StatusNarudzbine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaNarudzbine> StavkaNarudzbine { get; set; }
    }
}
