//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TepihServisManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StavkaNarudzbine
    {
        public int StavkaID { get; set; }
        public decimal Kvadratura { get; set; }
        public Nullable<decimal> Cijena { get; set; }
        public int NarudzbinaID { get; set; }
        public int TepihID { get; set; }
        public int UslugaID { get; set; }
    
        public virtual Narudzbina Narudzbina { get; set; }
        public virtual Tepih Tepih { get; set; }
        public virtual Usluga Usluga { get; set; }
    }
}
