//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TepihServisManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tepih
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tepih()
        {
            this.StavkaNarudzbine = new HashSet<StavkaNarudzbine>();
        }
    
        public int TepihID { get; set; }
        public string Naziv { get; set; }
        public string Tip { get; set; }
        public string Materijal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaNarudzbine> StavkaNarudzbine { get; set; }
    }
}
