//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TepihServisManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zaposleni
    {
        public int ZaposleniID { get; set; }
        public string Ime { get; set; }
        public string Pozicija { get; set; }
        public Nullable<decimal> Plata { get; set; }
    }
}
